### ISSUE TITLE
Create static snodas ui to replace snodas ui from django-ebagis

### ISSUE THREAD

**Issue by lbross** [PSU-CSAR/django-snodas#4]
The static content will be stored in a new snodas-ui folder at the root of django-snodas.  This folder will contain the standard subfolders under that: css, js, etc. We will need to add this path to the STATICFILES_DIRS variable so that the files are served correctly.

**Comment by lbross** [comment]
@jdduh: Do we want a help page for the web snodas tool? The current help button goes [here](http://webservices.geog.pdx.edu/ebagis/). I think this is a static page on the PSU BAGIS website.

**Comment by jkeifer** [comment]
I ended up having to pull the UI files out of this repo and they are now in https://github.com/PSU-CSAR/snodas-ui. Nonetheless, this issue has been completed.
